# Generated by Django 2.0.4 on 2018-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('flow', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
