# Generated by Django 2.0.4 on 2018-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_calc', '0002_interestflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoperation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interestflow',
            name='date',
            field=models.DateField(),
        ),
    ]
